import Link from 'next/link';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function TermsPage() {
  const domain = 'aipowar.com';

  return (
    <div className="flex flex-col min-h-screen">
      <header className="container mx-auto px-4 pt-8">
        <Link href="/">
          <h2 className="text-3xl font-bold font-headline text-transparent bg-clip-text bg-gradient-to-r from-primary to-accent">
            AI Powar
          </h2>
        </Link>
      </header>
      <main className="flex-1 container mx-auto px-4 py-8 md:py-16">
        <div className="max-w-4xl mx-auto">
          <Card className="rounded-2xl shadow-lg">
            <CardHeader>
              <CardTitle className="text-4xl font-extrabold text-center font-headline">Terms of Service & Privacy Policy</CardTitle>
            </CardHeader>
            <CardContent className="text-base text-muted-foreground space-y-8 px-8 pb-8">
              <section>
                <h3 className="text-2xl font-bold text-foreground mb-4">Terms of Service</h3>
                <div className="space-y-4">
                  <p>Welcome to AI Powar! By accessing our website, {domain}, you agree to be bound by these Terms of Service. Please read them carefully.</p>
                  <p><strong>Use of Service:</strong> AI Powar provides a free service for generating content ideas. You are free to use these ideas for personal or commercial purposes. You agree not to use the service for any illegal activities or to generate harmful or hateful content.</p>
                  <p><strong>Disclaimer:</strong> The content ideas are generated by an AI and are provided "as is". We make no warranties regarding the accuracy, originality, or suitability of the ideas. You are responsible for the content you create based on these suggestions.</p>
                  <p><strong>Limitation of Liability:</strong> AI Powar shall not be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the service.</p>
                  <p><strong>Changes to Terms:</strong> We reserve the right to modify these terms at any time. Your continued use of the service after any changes constitutes your acceptance of the new terms.</p>
                </div>
              </section>

              <div className="border-t border-border my-8"></div>

              <section>
                <h3 className="text-2xl font-bold text-foreground mb-4">Privacy Policy</h3>
                <div className="space-y-4">
                  <p>Your privacy is important to us. This policy explains what information we collect and how we use it.</p>
                  <p><strong>Information We Collect:</strong> We collect the topic or keyword you enter to generate ideas. We do not require you to create an account or provide any personal identification information (like name or email).</p>
                  <p><strong>How We Use Information:</strong> The topic you provide is sent to our AI model solely for the purpose of generating content ideas for your request. We do not store, sell, or share this input with third parties. We may temporarily log requests to monitor for abuse and to improve our service, but these logs are not tied to any personal information.</p>
                  <p><strong>Cookies:</strong> We do not use tracking cookies. We may use essential cookies for the basic functionality of the website.</p>
                  <p><strong>Your Consent:</strong> By using our website, you consent to our Privacy Policy.</p>
                  <p><strong>Contact Us:</strong> If you have any questions about this Privacy Policy, please contact us through our website.</p>
                </div>
              </section>

            </CardContent>
          </Card>
        </div>
      </main>
      <footer className="py-8 mt-12">
        <div className="container mx-auto text-center text-sm text-muted-foreground">
          <div className="flex justify-center gap-4 mb-2">
            <Link href="/about" className="hover:text-foreground">About</Link>
            <Link href="/terms" className="hover:text-foreground">Terms & Privacy</Link>
          </div>
          <p>&copy; {new Date().getFullYear()} AI Powar. Made with ❤️ in Pakistan.</p>
        </div>
      </footer>
    </div>
  );
}
